name : Windsor Food Collective
brand : wfc
description : Food buying collective in Brisbane
keyword : co-op, windsor food collective, nscf, northey st, northey street
url : http://windsorfoodcollective.github.io
email : hi@simonmcconnell.com
github : windsorfoodcollective
facebook: https://www.facebook.com/groups/1201331663262963/
author : Simon McConnell
year : 2016
markdown : kramdown
exclude :
  - node_modules
