name : Windsor Food Collective
brand : Windsor Food Collective
description : Food buying collective in Brisbane
keyword : co-op, windsor food collective, nscf, northey st, northey street
url : http://windsorfoodcollective.github.io
email : hi@simonmcconnell.com
github : windsorfoodcollective
author : Simon McConnell
year : 2016
markdown : kramdown
exclude :
  - node_modules
